package ru.givler.mbo.integration.caveabyss;

import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Loader;
import java.lang.reflect.Method;
import net.minecraft.block.material.Material;
import net.minecraft.world.World;
import net.minecraft.world.biome.BiomeGenBase;

/** Optional, cached bridge: MBO does not require CaveAbyss on its classpath. */
public final class FaunaCaveAbyss {
  private static boolean loaded;
  private static Method oceanBiome;

  private FaunaCaveAbyss() {}

  public static void init() {
    loaded = Loader.isModLoaded("caveabyss");
    oceanBiome = null;
    if (!loaded) return;
    try {
      oceanBiome =
          Class.forName("ru.givler.caveabyss.world.OceanCaves")
              .getMethod("isOceanBiome", BiomeGenBase.class);
    } catch (ReflectiveOperationException error) {
      FMLLog.warning(
          "[MBO fauna] CaveAbyss ocean API unavailable; using the approved ocean biome names.");
    }
  }

  public static boolean hasLowerLayer() {
    return loaded;
  }

  /**
   * Upper ocean caves generated by CaveAbyss grow upward from an unbroken lower-layer water column.
   */
  public static boolean isOceanCave(World world, int x, int y, int z) {
    if (!loaded
        || world.provider.dimensionId != 0
        || y < -50
        || y > 14
        || !isOcean(world.getBiomeGenForCoords(x, z))) return false;
    int bottom = y < 0 ? y : -1;
    for (int current = y; current >= bottom; current--)
      if (!world.blockExists(x, current, z)
          || world.getBlock(x, current, z).getMaterial() != Material.water) return false;
    return true;
  }

  public static boolean isOcean(BiomeGenBase biome) {
    if (biome == null) return false;
    if (oceanBiome != null) {
      try {
        return ((Boolean) oceanBiome.invoke(null, biome)).booleanValue();
      } catch (ReflectiveOperationException error) {
        oceanBiome = null;
        FMLLog.warning("[MBO fauna] CaveAbyss ocean query failed; using biome-name fallback.");
      }
    }
    String name = biome.biomeName;
    return name.equalsIgnoreCase("Ocean")
        || name.equalsIgnoreCase("Deep Ocean")
        || name.equalsIgnoreCase("FrozenOcean")
        || name.equalsIgnoreCase("Coral Reef")
        || name.equalsIgnoreCase("Kelp Forest");
  }
}
