package ru.givler.mbo.client.model.fauna;

/** Reference cube geometry; generated by tools/port_turtle_models.py. */
public final class ModelMBOAdultTurtle extends ModelMBOTurtle {
  public ModelMBOAdultTurtle() {
    super(128, 64);
    part("head", 0.0F, 19.0F, -10.0F, 0.0F, 0.0F, 0.0F);
    box("head", 3, 0, -3.0F, -1.0F, -3.0F, 6, 5, 6);
    part("body", 0.0F, 11.0F, -10.0F, 1.57079633F, 0.0F, 0.0F);
    box("body", 7, 37, -9.5F, 3.0F, -10.0F, 19, 20, 6);
    box("body", 31, 1, -5.5F, 3.0F, -13.0F, 11, 18, 3);
    part("egg_belly", 0.0F, 11.0F, -10.0F, 1.57079633F, 0.0F, 0.0F);
    box("egg_belly", 70, 33, -4.5F, 3.0F, -14.0F, 9, 18, 1);
    part("right_hind_leg", -3.5F, 22.0F, 11.0F, 0.0F, 0.0F, 0.0F);
    box("right_hind_leg", 1, 23, -2.0F, 0.0F, 0.0F, 4, 1, 10);
    part("left_hind_leg", 3.5F, 22.0F, 11.0F, 0.0F, 0.0F, 0.0F);
    box("left_hind_leg", 1, 12, -2.0F, 0.0F, 0.0F, 4, 1, 10);
    part("right_front_leg", -5.0F, 21.0F, -4.0F, 0.0F, 0.0F, 0.0F);
    box("right_front_leg", 27, 30, -13.0F, 0.0F, -2.0F, 13, 1, 5);
    part("left_front_leg", 5.0F, 21.0F, -4.0F, 0.0F, 0.0F, 0.0F);
    box("left_front_leg", 27, 24, 0.0F, 0.0F, -2.0F, 13, 1, 5);
  }
}
