package ru.givler.mbo.client.model.fauna;

/** Reference cube geometry; generated by tools/port_turtle_models.py. */
public final class ModelMBOBabyTurtle extends ModelMBOTurtle {
  public ModelMBOBabyTurtle() {
    super(16, 16);
    part("body", 0.0F, 22.9F, 1.0F, 0.0F, 0.0F, 0.0F);
    box("body", 0, 0, -2.0F, -1.0F, -2.0F, 4, 2, 4);
    part("head", 0.0F, 22.9F, -1.0F, 0.0F, 0.0F, 0.0F);
    box("head", 0, 6, -1.5F, -2.0F, -3.0F, 3, 3, 3);
    part("right_hind_leg", -2.0F, 23.9F, 2.5F, 0.0F, 0.0F, 0.0F);
    box("right_hind_leg", -1, 0, -2.0F, 0.0F, -0.5F, 2, 0, 1);
    part("left_hind_leg", 2.0F, 23.9F, 2.5F, 0.0F, 0.0F, 0.0F);
    box("left_hind_leg", -1, 1, 0.0F, 0.0F, -0.5F, 2, 0, 1);
    part("right_front_leg", -2.0F, 23.9F, -0.5F, 0.0F, 0.0F, 0.0F);
    box("right_front_leg", 8, 6, -2.0F, 0.0F, -0.5F, 2, 0, 1);
    part("left_front_leg", 2.0F, 23.9F, -0.5F, 0.0F, 0.0F, 0.0F);
    box("left_front_leg", 8, 7, 0.0F, 0.0F, -0.5F, 2, 0, 1);
  }
}
